# Generated by Django 2.0.7 on 2019-07-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='dealers_in',
        ),
        migrations.RemoveField(
            model_name='about',
            name='location',
        ),
        migrations.AddField(
            model_name='about',
            name='text',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
