# Generated by Django 2.0.7 on 2019-06-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190613_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacy',
            old_name='privacy',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='terms',
            old_name='term',
            new_name='text',
        ),
    ]
