# Generated by Django 2.0.7 on 2019-06-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190622_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='title',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='terms',
            name='title',
            field=models.CharField(default='', max_length=55),
        ),
    ]
